[package]
name = "staros-arch-aarch64"
description = "aarch64 architecture support: boot, MMU, exceptions, PL011 UART"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
staros-abi.workspace = true
staros-hal.workspace = true
staros-iommu.workspace = true
staros-mm.workspace = true
staros-videocore.workspace = true
